### ISSUE TITLE
[21 and above] FileNotFoundException when importing code to eclipse

### ISSUE THREAD

**Issue by jbrarAdobe** [adobe/aem-project-archetype#358]
### Expected Behaviour
Once the project is created using the archetype 21 and above, Importing to eclipse should not generate errors

### Actual Behaviour
Once the project is created using the archetype 21 and above, Importing to eclipse generates errors

#### Steps to Reproduce
- Use Archetype 21 and above to create a sample project using the command at [1]
[1] https://docs.adobe.com/content/help/en/experience-manager-learn/getting-started-wknd-tutorial-develop/project-setup.html#create
- Now, Import that project to Eclipse
- Notice that you run into following errors:

java.io.FileNotFoundException: /Users/eric/Columbia/Columbia-Projects/AEM/Development/aem_6_5_eclipse_workspace/cul/ui.apps.structure/target/classes (Is a directory) (org.apache.jackrabbit:filevault-package-maven-plugin:1.0.3:generate-metadata:default-generate-metadata:process-classes)

org.apache.maven.plugin.MojoExecutionException: java.io.FileNotFoundException: /Users/eric/Columbia/Columbia-Projects/AEM/Development/aem_6_5_eclipse_workspace/cul/ui.apps.structure/target/classes (Is a directory) 

#### Platform and Version
Archetype 21 and above
#### Logs taken while reproducing the problem

**Comment by kwin** [comment]
This should be fixed with filevault-package-maven-plugin 1.1.0.

**Comment by timdonovanuk** [comment]
Just the one error huh? Lucky you! I don't think I've ever got these archtypes created in Eclipse without at least a half dozen random errors and problems. 

```
Description	Resource	Path	Location	Type
Configured sync dir src/main/content/jcr_root does not exist	foo.all		Unknown	Sling IDE Validation Marker
Configured sync dir src/main/content/jcr_root does not exist	foo.ui.apps.structure		Unknown	Sling IDE Validation Marker
Could not add all necessary WTP natures: The set of natures is not valid.	pom.xml	/foo.all	line 1	Project Configurator Problem
Could not add all necessary WTP natures: The set of natures is not valid.	pom.xml	/foo.ui.apps	line 1	Project Configurator Problem
Could not add all necessary WTP natures: The set of natures is not valid.	pom.xml	/foo.ui.apps.structure	line 1	Project Configurator Problem
Could not add all necessary WTP natures: The set of natures is not valid.	pom.xml	/foo.ui.content	line 1	Project Configurator Problem
Execution default-generate-metadata of goal org.apache.jackrabbit:filevault-package-maven-plugin:1.0.3:generate-metadata failed: Unable to load the mojo 'generate-metadata' (or one of its required components) from the plugin 'org.apache.jackrabbit:filevault-package-maven-plugin:1.0.3' (org.apache.jackrabbit:filevault-package-maven-plugin:1.0.3:generate-metadata:default-generate-metadata:process-classes)

org.apache.maven.plugin.PluginExecutionException: Execution default-generate-metadata of goal org.apache.jackrabbit:filevault-package-maven-plugin:1.0.3:generate-metadata failed: Unable to load the mojo 'generate-metadata' (or one of its required components) from the plugin 'org.apache.jackrabbit:filevault-package-maven-plugin:1.0.3'
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:156)
	at org.eclipse.m2e.core.internal.embedder.MavenImpl.execute(MavenImpl.java:332)
	at org.eclipse.m2e.core.internal.embedder.MavenImpl.lambda$8(MavenImpl.java:1379)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:179)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:114)
	at org.eclipse.m2e.core.internal.embedder.MavenImpl.execute(MavenImpl.java:1378)
	at org.eclipse.m2e.core.project.configurator.MojoExecutionBuildParticipant.build(MojoExecutionBuildParticipant.java:54)
	at org.eclipse.m2e.core.internal.builder.MavenBuilderImpl.build(MavenBuilderImpl.java:135)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$1.method(MavenBuilder.java:169)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$1.method(MavenBuilder.java:1)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$BuildMethod.lambda$1(MavenBuilder.java:114)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:179)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:114)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$BuildMethod.lambda$0(MavenBuilder.java:105)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:179)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:153)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:101)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$BuildMethod.execute(MavenBuilder.java:88)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder.build(MavenBuilder.java:197)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:832)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:220)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:263)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:316)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:319)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:371)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:392)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:154)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:244)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: org.apache.maven.plugin.PluginContainerException: Unable to load the mojo 'generate-metadata' (or one of its required components) from the plugin 'org.apache.jackrabbit:filevault-package-maven-plugin:1.0.3'
	at org.apache.maven.plugin.internal.DefaultMavenPluginManager.getConfiguredMojo(DefaultMavenPluginManager.java:557)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:124)
	... 30 more
Caused by: org.codehaus.plexus.component.repository.exception.ComponentLookupException: java.util.NoSuchElementException
      role: org.apache.maven.plugin.Mojo
  roleHint: org.apache.jackrabbit:filevault-package-maven-plugin:1.0.3:generate-metadata
	at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:267)
	at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:255)
	at org.apache.maven.plugin.internal.DefaultMavenPluginManager.getConfiguredMojo(DefaultMavenPluginManager.java:520)
	... 31 more
Caused by: java.util.NoSuchElementException
	at org.eclipse.sisu.plexus.RealmFilteredBeans$FilteredItr.next(RealmFilteredBeans.java:118)
	at org.eclipse.sisu.plexus.RealmFilteredBeans$FilteredItr.next(RealmFilteredBeans.java:1)
	at org.eclipse.sisu.plexus.DefaultPlexusBeans$Itr.next(DefaultPlexusBeans.java:76)
	at org.eclipse.sisu.plexus.DefaultPlexusBeans$Itr.next(DefaultPlexusBeans.java:1)
	at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:263)
	... 33 more
	pom.xml	/foo.ui.content	line 46	Maven Build Problem
Plugin execution not covered by lifecycle configuration: org.apache.maven.plugins:maven-clean-plugin:2.4.1:clean (execution: auto-clean, phase: initialize)	pom.xml	/foo.all	line 102	Maven Project Build Lifecycle Mapping Problem
```

**Comment by timdonovanuk** [comment]
I get similar but different errors:

Description	Resource	Path	Location	Type
java.io.FileNotFoundException: C:\eclipse-workspace-2\foo\ui.apps.structure\target\classes (Access is denied) (org.apache.jackrabbit:filevault-package-maven-plugin:1.0.3:generate-metadata:default-generate-metadata:process-classes)

org.apache.maven.plugin.MojoExecutionException: java.io.FileNotFoundException: C:\eclipse-workspace-2\foo\ui.apps.structure\target\classes (Access is denied)
	at org.apache.jackrabbit.filevault.maven.packaging.GenerateMetadataMojo.execute(GenerateMetadataMojo.java:458)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
	at org.eclipse.m2e.core.internal.embedder.MavenImpl.execute(MavenImpl.java:332)
	at org.eclipse.m2e.core.internal.embedder.MavenImpl.lambda$8(MavenImpl.java:1379)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:179)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:114)
	at org.eclipse.m2e.core.internal.embedder.MavenImpl.execute(MavenImpl.java:1378)
	at org.eclipse.m2e.core.project.configurator.MojoExecutionBuildParticipant.build(MojoExecutionBuildParticipant.java:54)
	at org.eclipse.m2e.core.internal.builder.MavenBuilderImpl.build(MavenBuilderImpl.java:135)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$1.method(MavenBuilder.java:169)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$1.method(MavenBuilder.java:1)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$BuildMethod.lambda$1(MavenBuilder.java:114)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:179)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:114)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$BuildMethod.lambda$0(MavenBuilder.java:105)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:179)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:153)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:101)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$BuildMethod.execute(MavenBuilder.java:88)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder.build(MavenBuilder.java:197)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:832)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:220)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:263)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:316)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:319)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:371)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:392)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:154)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:244)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: java.io.FileNotFoundException: C:\eclipse-workspace-2\foo\ui.apps.structure\target\classes (Access is denied)
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(Unknown Source)
	at java.util.zip.ZipFile.<init>(Unknown Source)
	at java.util.zip.ZipFile.<init>(Unknown Source)
	at org.apache.jackrabbit.filevault.maven.packaging.impl.PackageInfo.read(PackageInfo.java:67)
	at org.apache.jackrabbit.filevault.maven.packaging.Dependency.resolve(Dependency.java:124)
	at org.apache.jackrabbit.filevault.maven.packaging.Dependency.resolve(Dependency.java:108)
	at org.apache.jackrabbit.filevault.maven.packaging.GenerateMetadataMojo.computeDependencies(GenerateMetadataMojo.java:710)
	at org.apache.jackrabbit.filevault.maven.packaging.GenerateMetadataMojo.execute(GenerateMetadataMojo.java:423)
	... 31 more
	pom.xml	/foo.ui.apps	line 47	Maven Build Problem
java.io.FileNotFoundException: C:\eclipse-workspace-2\foo\ui.apps\target\classes (Access is denied) (org.apache.jackrabbit:filevault-package-maven-plugin:1.0.3:generate-metadata:default-generate-metadata:process-classes)

org.apache.maven.plugin.MojoExecutionException: java.io.FileNotFoundException: C:\eclipse-workspace-2\foo\ui.apps\target\classes (Access is denied)
	at org.apache.jackrabbit.filevault.maven.packaging.GenerateMetadataMojo.execute(GenerateMetadataMojo.java:458)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
	at org.eclipse.m2e.core.internal.embedder.MavenImpl.execute(MavenImpl.java:332)
	at org.eclipse.m2e.core.internal.embedder.MavenImpl.lambda$8(MavenImpl.java:1379)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:179)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:114)
	at org.eclipse.m2e.core.internal.embedder.MavenImpl.execute(MavenImpl.java:1378)
	at org.eclipse.m2e.core.project.configurator.MojoExecutionBuildParticipant.build(MojoExecutionBuildParticipant.java:54)
	at org.eclipse.m2e.core.internal.builder.MavenBuilderImpl.build(MavenBuilderImpl.java:135)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$1.method(MavenBuilder.java:169)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$1.method(MavenBuilder.java:1)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$BuildMethod.lambda$1(MavenBuilder.java:114)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:179)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:114)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$BuildMethod.lambda$0(MavenBuilder.java:105)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:179)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:153)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:101)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$BuildMethod.execute(MavenBuilder.java:88)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder.build(MavenBuilder.java:197)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:832)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:220)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:263)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:316)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:319)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:371)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:392)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:154)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:244)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: java.io.FileNotFoundException: C:\eclipse-workspace-2\foo\ui.apps\target\classes (Access is denied)
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(Unknown Source)
	at java.util.zip.ZipFile.<init>(Unknown Source)
	at java.util.zip.ZipFile.<init>(Unknown Source)
	at org.apache.jackrabbit.filevault.maven.packaging.impl.PackageInfo.read(PackageInfo.java:67)
	at org.apache.jackrabbit.filevault.maven.packaging.Dependency.resolve(Dependency.java:124)
	at org.apache.jackrabbit.filevault.maven.packaging.Dependency.resolve(Dependency.java:108)
	at org.apache.jackrabbit.filevault.maven.packaging.GenerateMetadataMojo.computeDependencies(GenerateMetadataMojo.java:707)
	at org.apache.jackrabbit.filevault.maven.packaging.GenerateMetadataMojo.execute(GenerateMetadataMojo.java:423)
	... 31 more
	pom.xml	/foo.ui.content	line 46	Maven Build Problem

**Comment by kwin** [comment]
Let's try to identify the different issue and see whether there is already bug reports for those:


1. > Configured sync dir src/main/content/jcr_root does not exist

is already reported in https://github.com/adobe/aem-eclipse-developer-tools/issues/85

2. > Could not add all necessary WTP natures: 

This is IMHO not yet reported, please create a new issue at https://github.com/adobe/aem-eclipse-developer-tools/issue with the full stack trace and steps how to reproduce

3. > Execution default-generate-metadata of goal org.apache.jackrabbit:filevault-package-maven-plugin:1.0.3:generate-metadata failed: Unable to load the mojo 'generate-metadata' (or one of its required components) from the plugin 'org.apache.jackrabbit:filevault-package-maven-plugin:1.0.3'

This is obviously fixed by upgrade to FileVault 1.2.1.

4. > jackrabbit-filter: Node '/apps/msm/foo_blueprint' is not contained in any of the filter rules (org.apache.jackrabbit:filevault-package-maven-plugin:1.1.0:validate-files:default-validate-files:process-classes) .content.xml /foo.ui.apps/src/main/content/jcr_root/apps/msm/foo_blueprint line 3

This is not an Eclipse specific issue, and should be fixed in the context of https://github.com/adobe/aem-project-archetype/issues/325

**Comment by timdonovanuk** [comment]
Thanks @kwin it's great to see issues logged already exist for the majority of this. I can only implore Adobe and the maintainers of this repo to not make releases of the archetype that don't work or don't work with the tools and plugins provided by Adobe (i.e. the Eclipse plugin).

**Comment by timdonovanuk** [comment]
So WKND is using filevault-package-maven-plugin 1.1.0. and yet this error persists (actually persists is too strong a word, it comes and goes to be honest in Eclipse!).

If I set the /apps and /content project directories to remove Java and Dynamic Web Module project facets the error goes away, only to return when running a maven build. Running the maven build for some reason actually returns the Java and Dynamic Web Module facets back onto the directories, and hence this error comes back. @godanny86 any ideas?

**Comment by msagolj** [comment]
Verified that the exception no longer occurs when importing a project created with archetype 24 pre-release
